### ISSUE TITLE
ZLAC8015D Tuning

### ISSUE THREAD

**Issue by David9696** [rasheeddo/jmoab-ros#1]
Hi,

Thanks for sharing this great project.

May I know how do you tune the motors by using ZLAC8015D?

Thanks.

David[](url)

**Comment by rasheeddo** [comment]
> Hi,
> 
> Thanks for sharing this great project.
> 
> May I know how do you tune the motors by using ZLAC8015D?
> 
> Thanks.
> 
> David

Hi,
The 8 inch motors that came with ZLAC8015D driver are already plug and play, I didn't have to tune anything on motor. After the initialize step, and choosing the mode, then it's listening for the command and reply.

**Comment by David9696** [comment]
Hi,

Thanks for your reply.

I have a pair of 6.5 inches hub motor from ZLTECH. Thinking to buy a ZLAC8015D to try after found your great project. Do you think the 6.5 inches hub motor from ZLTECH would work with ZLAC8015D without tuning? 

Anyway, thanks for your info.

**Comment by rasheeddo** [comment]
I have tried to use ZLAC8015D with 10 inch motors, but it didn't work. The LED shows encoder wrong. So I guess, each driver is only compatible with its motor. How's your 6.5 inche motor's driver? it's not working well?

**Comment by embeddedengineer1515** [comment]
Hey hi,

I am really thankful to you initially i am using zlac8015d with rs485 by using Serial library but when i have seen your code on github the overall structure of my code has been changed. 


but still i have few doubts how you are converting distance travelled data into robot pose please help me on this.

thanks.

**Comment by NhatTran-97** [comment]
hello friend, how to calculate the cpr = 16385 in your code ?
